- name: configure the mysql server
  hosts: mysql
  become: yes
  vars: 
    mysql_password: ExpenseApp@1
  tasks:
  - name: install mysql libraries
    ansible.builtin.pip:
      name: "{{ item }}"
      state: installed
      executable: pip3.9
    loop: 
    - cryptography
    - PyMySQL

  - name: install mysql-server
    ansible.builtin.package: 
      name: mysql-server
      state: installed

  - name: start and enable msqld server
    ansible.builtin.service:
      name: mysqld
      state: started
      enabled: yes

  - name: connect to mysql-server
    community.mysql.mysql_info:
      login_user: root
      login_password: "{{ mysql_password }}"
      login_host: mysql.lakshman.site
    register: mysql_info 
    ignore_errors: true

  - name: print the mysql_info
    ansible.builtin.debug:
      msg: "Mysql_info {{ mysql_info }}"

  - name: setup root password 
    ansible.builtin.command: " mysql_secure_installation --set-root-pass {{ mysql_password }} "
    when: mysql_info.failed is true