- name: configure mysql-server
  hosts: mysql
  become: yes
  vars:
    mysql_password: ExpenseApp@1
  tasks: 
  - name: intsall mysql libraries
    ansible.builtin.pip:
      name: "{{ item }}"
      executable: pip3.9
    loop:
    - PyMySQL
    - cryptography

  - name: install mysql-server
    ansible.builtin.package:
      name: mysql-server
      state: installed

  - name: start and enable mysql-server
    ansible.builtin.service:
      name: mysqld 
      state: started 
      enabled: yes

  - name: connect to the mysql-server
    community.mysql.mysql_info:
      login_user: root
      login_password: "{{ mysql_password }}"
      login_host: mysql.lakshman.site
    register: mysql_info
    ignore_errors: true

  - name: print tthe mysql_info
    ansible.builtin.debug:
      masg: "{{ mysql_info }}"

  - name: setup root password
    ansible.builtin.command: " mysql_secure_installation --set-root-pass {{ mysql_password }} "



